### ISSUE TITLE
下载图片出现问题

### ISSUE THREAD

**Issue by CrazyBoyM** [nonebot/adapter-qqguild#10]
图片地址：https://wenxin.baidu.com/younger/file/ERNIE-ViLG/39d9837486e58bd78e74798e56017a535q

代码： 
```python
from nonebot import on_command
from nonebot.adapters.qqguild import MessageSegment

matcher = on_command("test")


@matcher.handle()
async def _():
    msg = MessageSegment.image("https://wenxin.baidu.com/younger/file/ERNIE-ViLG/39d9837486e58bd78e74798e56017a535q")
    await matcher.finish(msg)
```

报错：
```
08-26 19:01:43 [ERROR] nonebot | Running matcher <Matcher from drawer_bot.plugins.test, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\tsing\miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "c:\users\tsing\miniconda3\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "c:\users\tsing\miniconda3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\tsing\miniconda3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\tsing\miniconda3\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\users\tsing\miniconda3\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\tsing\miniconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\tsing\miniconda3\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "c:\users\tsing\miniconda3\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\users\tsing\miniconda3\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\users\tsing\miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "J:\myProject\机器人\nonebot2\drawer-bot\.\drawer_bot\plugins\test\__init__.py", line 10, in _
    await matcher.finish(msg)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\internal\matcher.py", line 468, in finish
    await cls.send(message, **kwargs)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\internal\matcher.py", line 453, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\adapters\qqguild\bot.py", line 144, in send
    return await self.post_messages(
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\adapters\qqguild\adapter.py", line 312, in _call_api
    return await api_handler(self, bot, **data)
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\adapters\qqguild\api\handle.py", line 275, in _post_messages
    return parse_obj_as(Message, await _request(adapter, bot, request))
  File "c:\users\tsing\miniconda3\lib\site-packages\nonebot\adapters\qqguild\api\request.py", line 34, in _request
    raise ActionFailed(data)
nonebot.adapters.qqguild.exception.ActionFailed: <ActionFailed: 500, code=40004, message=file not allow download, data=None>
```

**Comment by yanyongyu** [comment]
这个报错是频道返回的，可能是开发者平台没有正确配置url或者该图片地址不允许发送，详情可以咨询QQ机器人开发者频道

**Comment by CrazyBoyM** [comment]
https://avatars.githubusercontent.com/u/32300164?v=4 替换成这个地址是可以的

**Comment by yanyongyu** [comment]
这个问题我也不知道频道怎么处理的，你去问他们是不是屏蔽了百度，适配器只是把网址提交了而已，下载是腾讯下载的
