### ISSUE TITLE
配置好参数后启动后Bot(type='QQ Guild', self_id='*******') not found in adapter QQ Guild

### ISSUE THREAD

**Issue by Fanyu-Na** [nonebot/adapter-qqguild#48]
在安装好此适配器并且在nonebot加载适配器 然后配置好QQGUILD_BOTS等参数后启动nb会一直出现error

```python
08-08 12:36:46 [DEBUG] nonebot | QQ Guild | WebSocket Connection to wss://api.sgroup.qq.com/websocket established
08-08 12:36:46 [ERROR] nonebot | QQ Guild | Error while process data from websocket wss://api.sgroup.qq.com/websocket. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\Code\Python\python310\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\Code\Python\python310\lib\site-packages\nonebot\drivers\none.py", line 71, in run
    loop.run_until_complete(self._serve())
  File "D:\Code\Python\python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "D:\Code\Python\python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\Code\Python\python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "D:\Code\Python\python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "D:\Code\Python\python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Code\Python\python310\lib\site-packages\nonebot\adapters\qqguild\adapter.py", line 157, in _forward_ws
    result = await self._authenticate(bot, ws, shard)
  File "D:\Code\Python\python310\lib\site-packages\nonebot\adapters\qqguild\adapter.py", line 269, in _authenticate
    assert isinstance(
AssertionError: Received unexpected payload: InvalidSession(opcode=<Opcode.INVALID_SESSION: 9>, d=False)
08-08 12:36:46 [ERROR] nonebot | QQ Guild | Error while setup websocket to wss://api.sgroup.qq.com/websocket. Trying to reconnect...
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\Code\Python\python310\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\Code\Python\python310\lib\site-packages\nonebot\drivers\none.py", line 71, in run
    loop.run_until_complete(self._serve())
  File "D:\Code\Python\python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "D:\Code\Python\python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "D:\Code\Python\python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "D:\Code\Python\python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "D:\Code\Python\python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\Code\Python\python310\lib\site-packages\nonebot\adapters\qqguild\adapter.py", line 190, in _forward_ws
    self.bot_disconnect(bot)
  File "D:\Code\Python\python310\lib\site-packages\nonebot\internal\adapter\adapter.py", line 70, in bot_disconnect
    raise RuntimeError(f"{bot} not found in adapter {self.get_name()}")
RuntimeError: Bot(type='QQ Guild', self_id='******') not found in adapter QQ Guild
```

**Comment by yanyongyu** [comment]
请检查你的intent配置，私域才可以使用guild messages

**Comment by yanyongyu** [comment]
已解决
